metadata:
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/igalse/argocd-example-apps.git
    targetRevision: develop
    sysAppPath: eks-sit-usea1-1/system-apps
