apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-system-apps
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    path: eks-sit-usea1-1/system-apps/app-of-system-apps
    repoURL: https://votiro@dev.azure.com/votiro/Votiro/_git/gitops-dev
    targetRevision: develop
    helm:
      releaseName: applications
  project: default
