apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-system-apps
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    path: demo-k3d/system-apps/app-of-system-apps
    repoURL: https://github.com/igalse/argocd-example-apps.git
    targetRevision: develop
    helm:
      releaseName: applications
  project: default
